FROM python:alpine3.15

WORKDIR /app

RUN apk add --update gcc libc-dev linux-headers && rm -rf /var/cache/apk/* && \
    python3 -m pip install --upgrade pip setuptools

COPY . .

RUN pip3 install -r requirements.txt

CMD ["python3", "agent.py"]